SELECT
  PCLASS,
  INITCAP(P.DESCRIPTION) "CATEGORY",
  I.ITEM "ITEM #",
  VENDOR_ITEM "VENDOR #",
  UPPER(vend_name) "VENDOR NAME",
  MCODE,
  INITCAP(M.DESCRIPTION) "BRAND",
  --I.DESCRIPTION "ITEM DESCRIPTION",
  SUBSTR(I.DESCRIPTION,INSTR(I.DESCRIPTION, ',') +1 ) "ITEM DESCRIPTION",
  I.PKG "MASTER CASE",
  I.UOFM "UNIT",
  KOSHER,
  TO_CHAR(I.COST / 1000,'9999.000') "COST/UNIT",
  NVL(U.COST,0) "COST/MASTER CASE",
  I.LIST "LIST PRICE/UNIT",
  NVL(U.LIST,0) "LIST/MASTER CASE",
  SOLD_MTD,
  SOLD_YTD,
  I.QOH,
  COMMITTED,
  AVAILABLE,
  ON_ORDER,
  'LAST_ORD',
  'LAST_SOLD',
  '#OF CUST'
FROM
  IV_ITMFIL I,
  IV_MCODE M,
  IV_PCLASS P ,
  IV_STATUS S,
  AP_VENFIL V,
  ADDL_UOFM u
WHERE
  1           = 1
AND v.vend_id = I.PRIMARY_VENDOR
AND I.MCODE   = M.CODE
AND P.CLASS   = I.PCLASS
AND S.ITEM(+) = I.ITEM
and U.ITEM(+) = I.ITEM
ORDER BY 2;

